/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as GlossarioRouteImport } from './routes/glossario'
import { Route as ImprensaRouteImport } from './routes/imprensa'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AnalisesSlugRouteImport } from './routes/analises.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarioRoute = GlossarioRouteImport.update({
  id: '/glossario',
  path: '/glossario',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprensaRoute = ImprensaRouteImport.update({
  id: '/imprensa',
  path: '/imprensa',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisesSlugRoute = AnalisesSlugRouteImport.update({
  id: '/analises/$slug',
  path: '/analises/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/glossario': typeof GlossarioRoute
  '/imprensa': typeof ImprensaRoute
  '/sobre': typeof SobreRoute
  '/analises/$slug': typeof AnalisesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/glossario': typeof GlossarioRoute
  '/imprensa': typeof ImprensaRoute
  '/sobre': typeof SobreRoute
  '/analises/$slug': typeof AnalisesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/glossario': typeof GlossarioRoute
  '/imprensa': typeof ImprensaRoute
  '/sobre': typeof SobreRoute
  '/analises/$slug': typeof AnalisesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/glossario'
    | '/imprensa'
    | '/sobre'
    | '/analises/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/glossario'
    | '/imprensa'
    | '/sobre'
    | '/analises/$slug'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/glossario'
    | '/imprensa'
    | '/sobre'
    | '/analises/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  GlossarioRoute: typeof GlossarioRoute
  ImprensaRoute: typeof ImprensaRoute
  SobreRoute: typeof SobreRoute
  AnalisesSlugRoute: typeof AnalisesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario': {
      id: '/glossario'
      path: '/glossario'
      fullPath: '/glossario'
      preLoaderRoute: typeof GlossarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprensa': {
      id: '/imprensa'
      path: '/imprensa'
      fullPath: '/imprensa'
      preLoaderRoute: typeof ImprensaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analises/$slug': {
      id: '/analises/$slug'
      path: '/analises/$slug'
      fullPath: '/analises/$slug'
      preLoaderRoute: typeof AnalisesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  GlossarioRoute: GlossarioRoute,
  ImprensaRoute: ImprensaRoute,
  SobreRoute: SobreRoute,
  AnalisesSlugRoute: AnalisesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
